const wordDictionary = {
  "um técnico" : "uma técnica",
  "um planejador" : "uma planejadora",
  "um tapeceiro" : "uma tapeceira",
  "um supervisor" : "uma supervisora",
  "um soldador" : "uma soldadora",
  "um revisor" : "uma revisora",
  "um repositor" : "uma repositora",
  "um redator" : "uma redatora",
  "um químico" : "uma química",
  "um psicólogo" : "uma psicóloga",
  "um promotor" : "uma promotora",
  "um programador" : "uma programadora",
  "um professor" : "uma professora",
  "um preparador" : "uma preparadora",
  "um porteiro" : "uma porteira",
  "um podólogo" : "uma podóloga",
  "um pizzaiolo" : "uma pizzaiola",
  "um pesquisador" : "uma pesquisadora",
  "um padeiro" : "uma padeira",
  "um operador" : "uma operadora",
  "um engenheiro" : "uma engenheira",
  "um motoboy" : "uma motogirl",
  "um montador" : "uma montadora",
  "um mestre" : "uma mestra",
  "um mensageiro" : "uma mensageira",
  "um contador" : "uma contadora",
  "um veterinário" : "uma veterinária",
  "um médico" : "uma médica",
  "um confeiteiro" : "uma confeiteira",
  "um cobrador" : "uma cobradora",
  "um mecânico" : "uma mecânica",
  "um carpinteiro" : "uma carpinteira",
  "um caldeireiro" : "uma caldeireira",
  "um instrutor" : "uma instrutora",
  "um impressor" : "uma impressora",
  "um cabeleireiro" : "uma cabeleireira",
  "um bibliotecário" : "uma bibliotecária",
  "um degustador" : "uma degustadora",
  "um funileiro" : "uma funileira",
  "um fresador" : "uma fresadora",
  "um fonaudiólogo" : "uma fonaudióloga",
  "um ferramenteiro" : "uma ferramenteira",
  "um farmacêutico" : "uma farmacêutica",
  "um lancheiro" : "uma lancheira",
  "um auditor" : "uma auditora",
  "um executivo" : "uma executiva",
  "um encarregado" : "uma encarregada",
  "um arquiteto" : "uma arquiteta",
  "um apontador" : "uma apontadora",
  "um treinador" : "uma treinadora",
  "um advogado" : "uma advogada",
  "um vidraceiro" : "uma vidraceira",
  "um serralheiro" : "uma serralheira",
  "um retificador" : "uma retificadora",
  "um polidor" : "uma polidora",
  "um pintor" : "uma pintora",
  "um marceneiro" : "uma marceneira",
  "um mandrilhador" : "uma mandrilhadora",
  "um lubrificador" : "uma lubrificadora",
  "um laminador" : "uma laminadora",
  "um jardineiro" : "uma jardineira",
  "um extrusor" : "uma extrusora",
  "um eletrotécnico" : "uma eletrotécnica",
  "um eletromecânico" : "uma eletromecânica",
  "um cortador" : "uma cortadora",
  "um coordenador" : "uma coordenadora",
  "um camareiro" : "uma camareira",
  "um borracheiro" : "uma borracheira",
  "um barman" : "uma barwoman",
  "um afiador" : "uma afiadora",
  "um tesoureiro" : "uma tesoureira",
  "um torneiro" : "uma torneira",
  "um tosador" : "uma tosadora",
  "um vendedor" : "uma vendedora",
  "um zelador" : "uma zeladora",
  "um corretor" : "uma corretora",
  "um digitador" : "uma digitadora",
  "um diretor" : "uma diretora",
  "um embalador" : "uma embaladora",
  "um encanador" : "uma encanadora",
  "um divulgador" : "uma divulgadora",
  "um diretor" : "uma diretora",
  "um encarregado" : "uma encarregada",
  "um administrativo" : "uma administrativa",
  "um lavadeiro" : "uma lavadeira",
  "um diagramador" : "uma diagramadora",
  "um inspetor" : "uma inspetora",
  "um geólogo" : "uma geóloga",
  "um garçom" : "uma garçonete",
  "um enfermeiro" : "uma enfermeira",
  "um cozinheiro" : "uma cozinheira",
  "um assessor" : "uma assessora",
  "um administrador" : "uma administradora",
  "um biólogo" : "uma bióloga",
  "um biomédico" : "uma biomédica",
  "um bioquímico" : "uma bioquímica",
  "um consultor" : "uma consultora",
  "um office-boy" : "uma office-girl",
  "um estatístico" : "uma estatística",
  "um instalador" : "uma instaladora",
  "um matemático" : "uma matemática",
  "um publicitário" : "uma publicitária",
  "um tecnólogo" : "uma tecnóloga",
  "um agrônomo" : "uma agrônoma",
  "um boy" : "uma girl",
  "Técnico" : "Técnica",
  "Planejador" : "Planejadora",
  "Tapeceiro" : "Tapeceira",
  "Supervisor" : "Supervisora",
  "Soldador" : "Soldadora",
  "Revisor" : "Revisora",
  "Repositor" : "Repositora",
  "Redator" : "Redatora",
  "Químico" : "Química",
  "Psicólogo" : "Psicóloga",
  "Promotor" : "Promotora",
  "Programador" : "Programadora",
  "Professor" : "Professora",
  "Preparador" : "Preparadora",
  "Porteiro" : "Porteira",
  "Podólogo" : "Podóloga",
  "Pizzaiolo" : "Pizzaiola",
  "Pesquisador" : "Pesquisadora",
  "Padeiro" : "Padeira",
  "Operador" : "Operadora",
  "Engenheiro" : "Engenheira",
  "Motoboy" : "Motogirl",
  "Montador" : "Montadora",
  "Mestre" : "Mestra",
  "Mensageiro" : "Mensageira",
  "Contador" : "Contadora",
  "Veterinário" : "Veterinária",
  "Médico" : "Médica",
  "Confeiteiro" : "Confeiteira",
  "Cobrador" : "Cobradora",
  "Mecânico" : "Mecânica",
  "Carpinteiro" : "Carpinteira",
  "Caldeireiro" : "Caldeireira",
  "Instrutor" : "Instrutora",
  "Impressor" : "Impressora",
  "Cabeleireiro" : "Cabeleireira",
  "Bibliotecário" : "Bibliotecária",
  "Degustador" : "Degustadora",
  "Funileiro" : "Funileira",
  "Fresador" : "Fresadora",
  "Fonaudiólogo" : "Fonaudióloga",
  "Ferramenteiro" : "Ferramenteira",
  "Farmacêutico" : "Farmacêutica",
  "Lancheiro" : "Lancheira",
  "Auditor" : "Auditora",
  "Executivo" : "Executiva",
  "Encarregado" : "Encarregada",
  "Arquiteto" : "Arquiteta",
  "Apontador" : "Apontadora",
  "Treinador" : "Treinadora",
  "Advogado" : "Advogada",
  "Vidraceiro" : "Vidraceira",
  "Serralheiro" : "Serralheira",
  "Retificador" : "Retificadora",
  "Polidor" : "Polidora",
  "Pintor" : "Pintora",
  "Marceneiro" : "Marceneira",
  "Mandrilhador" : "Mandrilhadora",
  "Lubrificador" : "Lubrificadora",
  "Laminador" : "Laminadora",
  "Jardineiro" : "Jardineira",
  "Extrusor" : "Extrusora",
  "Eletrotécnico" : "Eletrotécnica",
  "Eletromecânico" : "Eletromecânica",
  "Cortador" : "Cortadora",
  "Coordenador" : "Coordenadora",
  "Camareiro" : "Camareira",
  "Borracheiro" : "Borracheira",
  "Barman" : "Barwoman",
  "Afiador" : "Afiadora",
  "Tesoureiro" : "Tesoureira",
  "Torneiro" : "Torneira",
  "Tosador" : "Tosadora",
  "Vendedor" : "Vendedora",
  "Zelador" : "Zeladora",
  "Corretor" : "Corretora",
  "Digitador" : "Digitadora",
  "Diretor" : "Diretora",
  "Embalador" : "Embaladora",
  "Encanador" : "Encanadora",
  "Divulgador" : "Divulgadora",
  "Diretor" : "Diretora",
  "Encarregado" : "Encarregada",
  "Administrativo" : "Administrativa",
  "Lavadeiro" : "Lavadeira",
  "Diagramador" : "Diagramadora",
  "Inspetor" : "Inspetora",
  "Geólogo" : "Geóloga",
  "Garçom" : "Garçonete",
  "Enfermeiro" : "Enfermeira",
  "Cozinheiro" : "Cozinheira",
  "Assessor" : "Assessora",
  "Administrador" : "Administradora",
  "Biólogo" : "Bióloga",
  "Biomédico" : "Biomédica",
  "Bioquímico" : "Bioquímica",
  "Consultor" : "Consultora",
  "Office-boy" : "Office-girl",
  "Estatístico" : "Estatística",
  "Instalador" : "Instaladora",
  "Matemático" : "Matemática",
  "Publicitário" : "Publicitária",
  "Tecnólogo" : "Tecnóloga",
  "Agrônomo" : "Agrônoma",
  "Boy" : "Girl"
};

function textNodesReplacer(node) {
  let allWords = [];
  for (node = node.firstChild; node; node = node.nextSibling) {
    if (node.nodeType == 3) allWords.push(node);
    else allWords = allWords.concat(textNodesReplacer(node));
  }
  return allWords;
}

let textNodes = textNodesReplacer(document.body);

for (node of textNodes) {
  let originalText = node.nodeValue;
  let text = originalText;
  for (wordToReplace in wordDictionary) {
    let maleWords = new RegExp("\\b(" + wordToReplace + ")\\b", "ig");
    let femaleWords = wordDictionary[wordToReplace]
    let replacedText = text.replace(maleWords, femaleWords);

    if (replacedText !== text && node.parentNode !== null) {
      text = replacedText;
    }
  }
  if (text != originalText && node.parentNode !== null) {
    let element = document.createElement("span");
    element.innerHTML = text;
    node.parentNode.replaceChild(element, node);
  }
}




